### ISSUE TITLE
Example does not work.

### ISSUE THREAD

**Issue by treeform** [tulayang/asyncmysql#1]
I really want to use this, I was looking for some thing like this as I want tot use mysql with async websockets in my game. I was very excited to see this but the example does not work and I want to figure out how to use this. 

It looks like library provides callback based API? And you wrap it in an async api? 

More documentation and simple examples would help! 

Thanks!

**Comment by treeform** [comment]
I managed to get it to work with this.

```
import asyncdispatch
import nativesockets
import mysqlparser
import asyncmysql

type
  Replies = seq[tuple[packet: ResultPacket, rows: seq[string]]]


proc execMyQuery(pool: AsyncMysqlPool, q: SqlQuery): Future[Replies] =
  var retFuture = newFuture[Replies]("execMyQuery")
  result = retFuture

  proc finishCb(err: ref Exception, replies: Replies) {.async.} =
    if err == nil:
      complete(retFuture, replies)
    else:
      fail(retFuture, err)

  execQuery(pool, q, finishCb)


proc main() =

  let db = waitFor openMysqlPool(
    domain = AF_INET, 
    port= Port(3306), 
    host = "127.0.0.1", 
    user = "user", 
    password = "pw", 
    database = "db", 
    capacity = 10
  )

  echo "connected to db" 

  let query = sql"""select name, email, token from players where nameLower like "tree%" """
  let replies = waitFor db.execMyQuery(query)

  echo "*", replies
  for packet in replies:   
    for i, data in packet.rows:
      if i mod packet.packet.fieldsCount == 0:
        echo "--"
      echo "  ", data

  echo "end"

main()
```

Some improvement suggestions:
* The mysqlparser should not leak out, just return seq of seq of strings for data, none of this packet field count blob of data stuff. 
* It looks like you provide a callback API/future hybrid api. I recommend just providing a future async waitFor api. 
* native sockets are leaking with AF_NET, I would just figure out if its IP, IPv2 or file inside the function based on parameters. Or just not support IPv2 or file for now?

**Comment by tulayang** [comment]
@treeform 

The current release (`nimble install`) you downloaded is an out-of-date version, its version is 0.2.1. I'm writing the document and I will release a new version this week, it contains the connection pool and callback API. 


> It looks like library provides callback based API? And you wrap it in an async api?

Yes, these basic API is callback-style and the callback proc must return a ``Future[T]``. 

> The mysqlparser should not leak out, just return seq of seq of strings for data, none of this packet field count blob of data stuff.

The mysqlparser will be hidden in the new release.

The purpose of return the packet field is to let the user confirm whether the MySQL query as expected. There are three kinds of the packet: ``rpkOk``, ``rpkError``, ``rpkResultSet``. For a ``insert`` or ``update`` query, the ``packet.kind`` should be ``rpkOk``, and a ``select`` query should be ``rpkResultSet`` and some rows. 

> It looks like you provide a callback API/future hybrid api. I recommend just providing a future async waitFor api

The use of callback proc is not based on preferences, but rather comes from a lot of tests and considerations. Using callbacks, asyncmysql can queue multiple requests (SQL queries) correctly, and handle large result sets on streaming. 

In practice, you can define your own wrapper proc to simplify programming. For example:

```nim
# wrap all the callbacks ...
proc myWrapProc(pool: AsyncMysqlPool): Future[void] = 
  var retFuture = newFuture[void]("myWrapProc")
  result = retFuture

  proc cb1(): Future[void] {.async.} = 
    await ...

  proc cb2(): Future[void] {.async.} = 
    await ...

  proc finishCb(err: ref Exception): Future[void] {.async.} = 
    await ...
    complete(retFuture) # or fail(retFuture, err)

  pool.execQuery(..., cb1, cb2, finishCb)

# the logical workflow
proc main() {.async.} =
  var pool = await openMysqlPool(...)
  await pool.myWrapProc()
  await ...
```

And this an example of streaming large result sets, it returns result field by field:

```nim
proc execQuery(pool: AsyncMysqlConnection): Future[void] =
  var retFuture = newFuture[void]("")
  result = retFuture
  var queryIx = 0

  proc recvPacketCb(packet: ResultPacket): Future[void] {.async.} =
    inc(queryIx)
    case queryIx
    of 1: 
      echo ">>> strart transaction;"
      echo packet
      assert packet.kind == rpkOk
    of 2: 
      echo ">>> select host, user from user where user = ?;"
      echo packet
      stdout.write("  ")
      assert packet.kind == rpkResultSet
    of 3: 
      echo ">>> select user from user;"
      echo packet
      stdout.write("  ")
      assert packet.kind == rpkResultSet
    of 4: 
      echo ">>> commit;"
      echo packet
      assert packet.kind == rpkOk
    else:
      discard

  proc recvPacketEndCb(): Future[void] {.async.} =
    case queryIx
    of 1: 
      discard
    of 2: 
      stdout.write("\n")
    of 3: 
      stdout.write("\n")
    of 4: 
      discard
    else:
      discard

  proc recvFieldCb(field: string): Future[void] {.async.} =
    case queryIx
    of 1: 
      discard
    of 2: 
      stdout.write(field, " ")
    of 3: 
      stdout.write(field, " ")
    of 4: 
      discard
    else:
      discard

  proc finishCb(err: ref Exception): Future[void] {.async.} =
    assert err == nil
    complete(retFuture)

  pool.execQuery(sql("""
start transaction;
select host, user from user where user = ?;
select user from user;
commit;
""", "root"), finishCb, recvPacketCb, recvPacketEndCb, recvFieldCb)

proc main() {.async.} =
  let pool = await openMysqlPool(AF_INET, MysqlPort, MysqlHost, MysqlUser, MysqlPassword, MysqlDatabase)
  await pool.execQuery()
  pool.close()

waitFor main() 
``` 

> native sockets are leaking with AF_NET, I would just figure out if its IP, IPv2 or file inside the function based on parameters. Or just not support IPv2 or file for now?

Currently, IPv4 (``AF_NET``) and IPv6 (``AF_NET6``) are supported, and UNIX domain socket is not supported.

**Comment by treeform** [comment]
Thank you for your reply!

I have the version from your github. I am hacking a way on it too. I run into a really major bug for me here: https://github.com/tulayang/asyncmysql/issues/2 .

It took me a while to get a hang of this async callback future stuff, but I think i got it. But I do wish the API was easier. I am making my own api on top of your api. I am trying to mimic more how the stdlib mysql package works for easy porting.

I saw that AF_NET is default. I pretty much ignore that now and native sockets.

**Comment by tulayang** [comment]
Without callback API, there will be a lot of pitfalls when using the stream procs. [JDBC](https://dev.mysql.com/doc/connector-j/5.1/en/connector-j-reference-implementation-notes.html) has **caveats** when stream result sets row-by-row:

> By default, ResultSets are completely retrieved and stored in memory. In most cases this is the most efficient way to operate and, due to the design of the MySQL network protocol, is easier to implement. If you are working with ResultSets that have a large number of rows or large values and cannot allocate heap space in your JVM for the memory required, you can tell the driver to stream the results back one row at a time.

> To enable this functionality, create a Statement instance in the following manner.

> The combination of a forward-only, read-only result set, with a fetch size of Integer.MIN_VALUE serves as a signal to the driver to stream result sets row-by-row. After this, any result sets created with the statement will be retrieved row-by-row.

> There are some **caveats** with this approach. You must read all of the rows in the result set (or close it) before you can issue any other queries on the connection, or an exception will be thrown.

However, callbacks can avoid these **caveats**. They  provide a lightweight interface, and always correctly queue the result sets.

**Comment by tulayang** [comment]
So, I'd close this issue.
