### ISSUE TITLE
Fails to SELECT large fields, just hangs.

### ISSUE THREAD

**Issue by treeform** [tulayang/asyncmysql#2]
I have a branch and a test suite to reproduce the bug here: 
https://github.com/tulayang/asyncmysql/compare/master...treeform:largerawbug?expand=1#diff-157a7777fbef0660aaf774109a2e2f39R516

Test case simply does:
```
insert into sample(val) values (aaaaaaa..... 1 million of them ...... aaaaaaaa);
>>> works
select * from sample;
>>> hangs
```

After fighting through the code I think that the last `rsetRowEof` is never getting read. Either its not sent by mysql for large results or its simply getting forgotten some how during parsing. The `rsetRow`  and `rsetRowHeader` seem to all make it and structures populate but never are returned due to missing `rsetRowEof`.

**Comment by tulayang** [comment]
This is a bug in both **mysqlparser** and **asyncmysqll**, and this has been solved in the latest version. Thanks for the report.

And, I have appended your test to the latest unit test. see [L516 test](https://github.com/tulayang/asyncmysql/blob/master/test/test_connection.nim#L516)

**Comment by treeform** [comment]
Thanks. I have tested this and it works! I am glad you used my code in the test suite.
